### ISSUE TITLE
Volume always 100% after page refresh

### ISSUE THREAD

**Issue by coffeepanda** [Trikolon/liquidradio#25] opened 2017-07-09 12:45 UTC
... when using the volume buttons after that, it behaves as if it had actually remembered the previously saved volume. Example/recreation: play stream, set the volume to 10%, refresh the page, press play again (volume is at 100%) and then use volume down (volume jumps to 0%)

**Comment by Trikolon** [comment] 2017-07-09 14:36
duplicate of #20

**Closed by Trikolon** 2017-07-09 14:36 UTC
